server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 127.0.0.1
    username: /guest
    password: guest
    #virtual-host: /leyou
    template:
      retry:
        enabled: true
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 210000ms
      exchange: leyou.item.exchange
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}